### ISSUE TITLE
Help maintainers to package nemex

### ISSUE THREAD

**Issue by brejoc** [neonelephantstudio/nemex#10]
As far as I can see you don't use tags or branches to mark versions in git and the downloads from your website point to http://nemex.io/nemex.zip without a version scheme.

If I'd like to package nemex I'd have to download a specific version of it and also be able to download that version some day in the future. I could make and maintain a snapshot of the sources, but that is a job you are better suited for and other package maintainers would also benefit from.

**Comment by phoboslab** [comment]
Yes, the next version will be 1.1. We also put the version number on the website. Thanks!

**Comment by brejoc** [comment]
Very nice. Thanks!
