### ISSUE TITLE
non-executable php config file

### ISSUE THREAD

**Issue by floriangosse** [neonelephantstudio/nemex#19]
Are there any plan to use a config file which is not executable like json, yaml?

**Comment by phoboslab** [comment]
What would be the benefit of this?

I can only see one big drawback: securing the config file (from direct access via http) would be another step, webserver specific and easily forgotten.

**Comment by floriangosse** [comment]
I think it's cleaner to put the config in a known structured file because some people doesn't know php. 

For the config file is no protection needed if the executable sources are in a subfolder. Other php projects use a similiar structure.

example:
```
nemex
├── config.json
├── license.txt
├── readme.md
└── public/
    ├── api.php
    ├── config.php
    ├── index.php
    ├── lib/
    └── media/
```

The document root will be `path/of/nemex/public`

**Comment by 2braincells2go** [comment]
Config file make the most sense to me. Have used them for years and if they execute in a users browser something terribly wrong...

**Comment by phoboslab** [comment]
@floriangosse the directory structure you propose isn't configurable on many shared hosts were you can't change the document root. We want nemex to run on really small web hosting packages, without any special settings. 

Also, I don't think the current `config.php` is easily understandable, even if you know nothing about PHP. I'd be happy to make the `config.php` even easier to understand if you have any suggestions, but I don't think putting the password in a static file is a good idea.

@2braincells2go executing the current config.php will not output anything and will not produce any errors.

**Comment by 2braincells2go** [comment]
My bad @phoboslab, misunderstood what you meant:

"I can only see one big drawback: securing the config file (from direct access via http) would be another step, webserver specific and easily forgotten."

**Comment by floriangosse** [comment]
To secure the plain config file you can use a .htaccess file.

**Comment by phoboslab** [comment]
That's the extra step we're trying to avoid :)
Sorry, I don't see the benefit of this. It would actually make things more complicated for a lot of users.
